services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - 27017:27017
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'localhost:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      retries: 30
    volumes:
      - "mongo_data:/data/db"
      - "mongo_config:/data/configdb"
    networks:
      - mongo-net

  restapi:
    image: python:3.14-rc-alpine3.21
    container_name: rest_api
    working_dir: /app
    volumes:
      - ./rest-api:/app/rest-api
      - ./pylib:/app/pylib
    environment:
      - PYTHONPATH=/app:/app/pylib
      - DB_NAME=simlab
      - MONGO_URI=mongodb://mongodb:27017/?replicaSet=rs0
    ports:
      - "8000:8000"
    command: >
      sh -c "
      pip install --no-cache-dir -r /app/rest-api/requirements.txt &&
      python /app/rest-api/main.py
      "
    depends_on:
      - mongodb
    networks:
      - mongo-net

  masternode:
    image: python:3.14-rc-alpine3.21
    container_name: master_node
    working_dir: /app
    volumes:
      - ./master-node:/app/master-node
      - ./pylib:/app/pylib
    environment:
      - PYTHONPATH=/app:/app/pylib
      - DB_NAME=simlab
      - MONGO_URI=mongodb://mongodb:27017/?replicaSet=rs0
    ports:
      - "2220:22"
    command: >
      sh -c "
      pip install --no-cache-dir -r /app/rest-api/requirements.txt &&
      python /app/master-node/main.py
      "
    depends_on:
      - mongodb
    networks:
      - mongo-net
      - cooja-net

  cooja1:
    image: juniocesarferreira/simulation-cooja:v1.1
    container_name: cooja1
    restart: unless-stopped
    ports:
      - "2231:22"
    networks:
      - cooja-net

  cooja2:
    image: juniocesarferreira/simulation-cooja:v1.1
    container_name: cooja2
    restart: unless-stopped
    ports:
      - "2232:22"
    networks:
      - cooja-net

  cooja3:
    image: juniocesarferreira/simulation-cooja:v1.1
    container_name: cooja3
    restart: unless-stopped
    ports:
      - "2233:22"
    networks:
      - cooja-net

  cooja4:
    image: juniocesarferreira/simulation-cooja:v1.1
    container_name: cooja4
    restart: unless-stopped
    ports:
      - "2234:22"
    networks:
      - cooja-net

  cooja5:
    image: juniocesarferreira/simulation-cooja:v1.1
    container_name: cooja5
    restart: unless-stopped
    ports:
      - "2235:22"
    networks:
      - cooja-net

volumes:
  mongo_data:
  mongo_config:

networks:
  mongo-net:
    name: mongo_net
    driver: bridge
  cooja-net:
    name: cooja_net
    driver: bridge