version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  restapi:
    build: ./rest-api/SimApi
    container_name: restapi
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - mongodb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MONGO_URI=mongodb://mongodb:27017

volumes:
  mongo_data:
